name: Lightweight - Java Tests

on:
  workflow_call:
    inputs:
      SINK_CONNECTOR_IMAGE:
        description: "Lightweight connector docker image"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      SINK_CONNECTOR_IMAGE:
        description: "Lightweight connector docker image"
        required: true
        type: string

env:
  SINK_CONNECTOR_IMAGE: ${{ inputs.SINK_CONNECTOR_IMAGE }}

jobs:
  java-lightweight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Display hostname of runner
        run: echo $(hostname -I | cut -d ' ' -f 1)
      - name: Install maven
        run: sudo apt-get update && sudo apt-get install -y maven
      - name: Build Library with Maven
        working-directory: sink-connector
        run: mvn clean install -DskipTests=true
      - name: Build Replicator with Maven
        working-directory: sink-connector-lightweight
        run: mvn --quiet surefire-report:report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'sink-connector-lightweight/target/surefire-reports/TEST-*.xml'
